MoviePedia/MoviePedia/urls.py
from django.contrib import admin
from django.urls import path, include
# from register_login.views import IndexPageView
from register_login import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('register_login/', include('register_login.urls')),
    path('movies/', include('movies.urls')),
    path('film/', include('film.urls')),
    path('logout/', views.user_logout, name = 'logout'),
    # path('login/', views.user_logout, name = 'login'),
    path('admin/', admin.site.urls),
]

MoviePedia/film/urls.py
from django.urls import path, re_path
from . import views

app_name = 'film'

urlpatterns = [
    path('<int:pk>', views.FilmDetailView, name = 'detail'),
]

MoviePedia/register_login/urls.py
from django.urls import path
from . import views
# from .views import IndexPageView, register
from .views import register

app_name = 'register_login'

urlpatterns = [
    path('user_login/', views.user_login, name = 'user_login' ),
    path('register/', views.register, name = 'register')
]

MoviePedia/register_login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    profile_pic = models.ImageField(upload_to = 'profile_pic', blank = True)

    def __str__(self):
        return self.user.username

MoviePedia/register_login/forms.py
from django import forms
from . models import UserProfileInfo
from db.models import Film
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
        
class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('profile_pic',)

class FilmListForm(forms.ModelForm):
    class Meta():
        model = Film
        fields = ('title', 'year')

MoviePedia/register_login/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView
from register_login.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from .forms import FilmListForm
from db.models import Film

def index(request):
    if request.method == 'POST':
        title_form = request.POST.get('title')
        year_form = request.POST.get('year')

        if title_form and year_form:
            film = Film.objects.filter(title__icontains = title_form, year = int(year_form))
            if film:
                count = len(film)
                count_message = f"I have found {count} positions."
            else:
                film = Film.objects.all()
                count = len(film)
                count_message = f"I have found 0 movies for your request so let me show you my whole collection of {count} positions."
        elif title_form:
            film = Film.objects.filter(title__icontains = title_form)
            if film:
                count = len(film)
                count_message = f"I have found {count} positions."
            else:
                film = Film.objects.all()
                count = len(film)
                count_message = f"I have found 0 movies for your request so let me show you my whole collection of {count} positions."
        elif year_form:
            film = Film.objects.filter(year = int(year_form))
            if film:
                count = len(film)
                count_message = f"I have found {count} positions."
            else:
                film = Film.objects.all()
                count = len(film)
                count_message = f"I have found 0 movies for your request so let me show you my whole collection of {count} positions."
        else:
            film = Film.objects.all()
            count = len(film)
            count_message = f"I have found 0 movies for your request so let me show you my whole collection of {count} positions."

        return render(request, 'register_login/index.html',{'film':film,
                                                        'count_message':count_message})
    else:
        return render(request, 'register_login/index.html',{})

@login_required
def user_logout(request):
    logout(request)

    return HttpResponseRedirect(reverse('index'))

def user_login(request):
    warning = ''
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            warning = 'Invalid login details supplied.'
            return render(request, 'register_login/login.html', {'warning':warning})

    else:
        return render(request, 'register_login/login.html', {})

def register(request):
    warning = ''
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

                profile.save()

                registered = True

            warning = 'Succesfully added'

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'register_login/registration.html', {'user_form':user_form,
                                                                'profile_form':profile_form,
                                                                'registered':registered,
                                                                'warning':warning})

MoviePedia/templates/register_login/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <nav class = "navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">MoviePedia</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class = 'navbar-nav'>
          <li class="nav-item">
            <a class = 'nav-link' href="{% url 'register_login:register' %}">Register</a>
          </li>

            {% if user.is_authenticated %}

            <li class = "nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>

            {% else %}

            <li class = "nav-item">
              <a class="nav-link" href="{% url 'register_login:user_login' %}">Login</a>
            </li>

            {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

MoviePedia/templates/register_login/index.html
<!DOCTYPE html>
{% extends 'register_login/base.html' %}
{% block body_block %}
{% load staticfiles %}


<h1>Check our films' database!</h1>
<div class="container">
<form method = "POST" action="">
  {% csrf_token %}
  <div class="form-row">
    <div class="col">
      <input type="text" id = "title" name = 'title' class="form-control" placeholder="Title" value = "{{ current_title }}">
    </div>
    <div class="col">
      <input type="number" id = "year" name = "year" class="form-control" placeholder="Year" value = "{{ current_year }}" min = "1900">
    </div>
    <input type = "submit" class="btn btn-primary" value="Search"
  </div>
</form>
</div>

{% if film %}
  <div class="alert alert-light" role="alert">
    {{count_message}}
  </div>
  <div class="list-group">
    {% for i in film %}
    <a href="{% url 'film:detail' i.id %}" class="list-group-item list-group-item-action">
      {{i}} from {{i.year}}
    </a>
    {% endfor %}
  </div>
{% endif %}
{% endblock %}

MoviePedia/templates/register_login/login.html
{% extends 'register_login/base.html'%}

{% block body_block%}
  <h3>Please login</h3>
  <form action="{% url 'register_login:user_login' %}" method="post">
    {% csrf_token %}
    <div class="form-row">
      <div class="col">
        <input type="text" name = "username" class="form-control" placeholder="Username">
      </div>
      <div class="col">
        <input type="password" id="inputPassword" name = "password" class="form-control" placeholder="Password">
      </div>
    </div>
    <input type="submit" class="btn btn-primary" value="Log in">
  </form>

  {% if warning %}
    <div class="alert alert-danger" role="alert">
      {{warning}}
    </div>
  {% endif %}
{% endblock %}

MoviePedia/templates/register_login/registration.html
<!DOCTYPE html>
{% extends 'register_login/base.html' %}
{% load staticfiles %}
{% block body_block %}

  {% if registered %}
    <h1>Thank you for registering!</h1>
  {% else %}
    <h3>Fill out the form:</h3>

    <form method="POST"enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">

      </div>
      {{user_form.as_p}}
      {{ profile_form.as_p }}
      <input type="Submit" class="btn btn-primary" value="Register">
    </form>
    {% if warning %}
      <div class="alert alert-success" role="alert">
        {{warning}}
      </div>
    {% endif %}
  {% endif %}
{% endblock %}